# @generated by https://codeberg.org/goldstein/unflake
let
  deps = rec {
    unflake_github_nix-community_home-manager = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "home-manager";
      rev = "ae8003d8b61d0d373e7ca3da1a48f9c870d15df9";
      lastModified = 1771188132;
      narHash = "sha256-qLXxN/tPrZtnekaLBQuVtxQfvqqs5cT5WbyH4zZaTGI=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "a82ccc39b39b621151d6732718e3e250109076fa";
      lastModified = 1771008912;
      narHash = "sha256-gf2AmWVTs8lEq7z/3ZAsgnZDhWIckkb+ZnAo5RzSxJg=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "e3cb16bccd9facebae3ba29c6a76a4cc1b73462a";
      lastModified = 1771147098;
      narHash = "sha256-jpfPdBjKO232s5NueoNEvvVzpndiUzPLNYcH4/Ov0gY=";
    };
    unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz = builtins.fetchTree {
      type = "tarball";
      url = "https://codeberg.org/api/v1/repos/goldstein/unflake/archive/cd4807d72059019f6b35f63b60af58a37d994ffe.tar.gz";
      lastModified = 1771185468;
      narHash = "sha256-RlGkE4IMxDWiazSDCnE/FduLqm1Hwodg21bzH4UaIAs=";
    };
  };
  universe = rec {
    unflake_github_nix-community_home-manager = ((import "${deps.unflake_github_nix-community_home-manager.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_home-manager;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_home-manager // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_home-manager.outPath}";
      sourceInfo = deps.unflake_github_nix-community_home-manager;
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    };
    unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz = ((import "${deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz.outPath}/flake.nix").outputs {
      self = unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz // {
      _flake = true;
      outPath = "${deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz.outPath}";
      sourceInfo = deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz;
    };
  };
  inputs = {
    home-manager = universe.unflake_github_nix-community_home-manager;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    unflake = universe.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs = outputs: let self = outputs (inputs // { inherit self; }); in self;
    __functor = self: self.withInputs;
  };
in inputs