[".config/nvim"]
type = "git-repo"
url = "https://github.com/Cricarvbnm/cfg-lazyvim.git"
refreshPeriod = "1h"

[".local/opt/nvidia-laptop-power-cfg"]
type = "git-repo"
url = "https://gitlab.com/asus-linux/nvidia-laptop-power-cfg.git"
refreshPeriod = "168h"
