[".config/nvim"]
type = "git-repo"
url = "https://github.com/Cricarvbnm/cfg-lazyvim.git"
refreshPeriod = "1h"

# Following Projects

["dev/follow/nvidia-laptop-power-cfg"]
type = "git-repo"
url = "https://gitlab.com/asus-linux/nvidia-laptop-power-cfg.git"
refreshPeriod = "168h"

["dev/follow/nvidia-laptop-power-cfg".clone]
args = ["--depth=1"]

# My Working Projects
["dev/tieba-sign"]
type = "git-repo"
url = "https://github.com/Cricarvbnm/tieba-sign-go.git"
refreshPeriod = "168h"

["dev/save-music"]
type = "git-repo"
url = "https://github.com/Cricarvbnm/save-music.git"
refreshPeriod = "168h"

["dev/gistow"]
type = "git-repo"
url = "https://github.com/Cricarvbnm/gistow.git"
refreshPeriod = "168h"
