general {
  after_sleep_cmd=niri msg action power-off-monitors
  ignore_dbus_inhibit=false
  lock_cmd=qs -c noctalia-shell ipc call lockScreen lock
}

listener {
  on-timeout=qs -c noctalia-shell ipc call lockScreen lock
  timeout=600
}

listener {
  // Power off monitors only if the user session is locked
  on-timeout=sh -c '[ $(loginctl show-session $(loginctl list-sessions --no-legend | awk -v u=$(id -u) '\''$2==u&&($5~/seat/||$6=="user"){print$1;exit}'\'') -p LockedHint --value) = yes ]' && niri msg action power-off-monitors

  on-resume=niri msg action power-on-monitors
  timeout=5
}
